export const NavBox: object = {
  width: window.innerWidth * 0.23,
  minWidth: '315px',
  position: 'fixed',
  backgroundColor: 'white',
  zIndex: 99,
  right: '1.5rem',
  top: '1.5rem',
  height: 65,
  borderRadius: '5px',
  boxShadow: 2,
  display: 'flex',
  flexWrap: 'wrap',
  justifyItems: 'center',
  justifyContent: 'center',
  float: 'right',
}
